id: leng-qie-jing
meta:
  title:
    zh: 楞伽阿跋多羅寶經
    sa: Laṅkāvatāra Sūtra
    short: 楞伽經
  author: 求那跋陀羅
  pdf:
    title: 楞伽阿跋多羅寶經
    author: 求那跋陀羅
    subject: 佛教經典
    keywords: 楞伽阿跋多羅寶經, 楞伽經, Laṅkāvatāra Sūtra, 求那跋陀羅, 佛教經典
  cbeta:
    id: T0670
  version: v0.2.0
  versionDate: 2026-03-22
files:
  - name: T0670_001.txt
  - name: T0670_002.txt
  - name: T0670_003.txt
  - name: T0670_004.txt
