id: shi-xiao-zhou
meta:
  title:
    short: 十小咒
  author: ""
  pdf:
    title: 十小咒
    author: "n/a"
    subject: 佛教經典
    keywords: 十小咒, 佛教經典
  cbeta:
    id: "n/a"
  version: v0.9.0
  versionDate: 2026-03-20
files:
  - name: sutra.txt
