id: xin-jing
meta:
  title:
    zh: 般若波羅蜜多心經
    sa: Prajñāpāramitāhṛdaya
    short: 心經
  author: 玄奘
  subject: 佛教經典
  keywords: 般若波羅蜜多心經, 心經, 玄奘, 佛教經典
  cbeta:
    id: T0251
  version: v1.0.0
  versionDate: 2026-03-17
files:
  - name: sutra.txt
