id: leng-yan-jing
meta:
  title:
    zh: 大佛頂如來密因修證了義諸菩薩萬行首楞嚴經
    short: 楞嚴經
  author: 般剌蜜帝
  pdf:
    title: 大佛頂如來密因修證了義諸菩薩萬行首楞嚴經
    author: 般剌蜜帝
    subject: 佛教經典
    keywords: 大佛頂如來密因修證了義諸菩薩萬行首楞嚴經, 楞嚴經, 般剌蜜帝, 佛教經典
  cbeta:
    id: T0945
  version: v0.1.0
  versionDate: 2026-03-23
files:
  - name: T0945_001.txt
  - name: T0945_002.txt
  - name: T0945_003.txt
  - name: T0945_004.txt
  - name: T0945_005.txt
  - name: T0945_006.txt
  - name: T0945_007.txt
  - name: T0945_008.txt
  - name: T0945_009.txt
  - name: T0945_010.txt
