佛: [['fó']]
南無: [["nā"], ["mó"]]
阿耨多羅: [["ā"], ["nòu"], ["duō"], ["luó"]]
三藐三菩提: [["sān"], ["miǎo"], ["sān"], ["pú"], ["tí"]]
祇樹給孤獨園: [["qí"], ["shù"], ["jǐ"], ["gū"], ["dú"], ["yuán"]]
怛姪他: [["dá"], ["zhí"], ["tā"]]
唵: [["ōm"]]
伽: [["qié"]]
娑婆訶: [["suō"], ["pó"], ["hē"]]
薄伽梵: [["bó"], ["qié"], ["fàn"]]

縛: [["fú"]]
相: [["xiàng"]]
為: [["wéi"]]
得: [["dé"]]
