佛: [['fó']]
南無: [["nā"], ["mó"]]
阿耨多羅: [["ā"], ["nòu"], ["duō"], ["luó"]]
三藐三菩提: [["sān"], ["miǎo"], ["sān"], ["pú"], ["tí"]]
祇樹給孤獨園: [["qí"], ["shù"], ["jǐ"], ["gū"], ["dú"], ["yuán"]]
怛姪他: [["dá"], ["zhí"], ["tā"]]
唵: [["ōm"]]
伽: [["qié"]]
娑婆訶: [["suō"], ["pó"], ["hē"]]
薄伽梵: [["bó"], ["qié"], ["fàn"]]
尸羅: [["shī"], ["luó"]]
俱胝: [["jù"], ["zhī"]]

夜叉: [["yè"], ["chā"]]
乾闥婆: [["qián"], ["tà"], ["pó"]]
阿脩羅: [["ā"], ["xiū"], ["luó"]]
迦樓羅: [["jiā"], ["lóu"], ["luó"]]
緊那羅: [["jǐn"], ["nà"], ["luó"]]
摩睺羅伽: [["mó"], ["hóu"], ["luó"], ["jiā"]]

縛: [["fú"]]
相: [["xiàng"]]
為: [["wéi"]]
所得: [["suǒ"], ["dé"]]
