name: Test build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: siakhooi/devcontainer:latex
      options: --user root
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: build
        run: |
          export PYENV_ROOT="/home/maui/.pyenv"
          export PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv versions
          ./scripts/build-all-pdf.sh
